name: coffee_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  location: ^6.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  yandex_mapkit: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
